"""Loads the catalog CSVs — real South African unit trusts and Liberty
products now, not hackathon placeholders.

Big change from the original hackathon version: portfolio returns are
no longer hand-typed. portfolio_returns.csv is itself GENERATED by a
separate script (asset_class_returns.py) that blends 10 asset-class
return assumptions by each fund's actual weightings — this module just
reads the finished curve, one row per (portfolio, horizon_years), for
every integer year 1-100. That script's output is in DECIMAL FRACTION
form (0.0616 = 6.16%); everywhere else in this app (Pydantic models,
frontend display, projections.py) expects PERCENTAGE numbers (6.16),
so the x100 conversion happens once here, at the boundary.
"""

from __future__ import annotations

import csv
from pathlib import Path

DATA_DIR = Path(__file__).parent / "data"


def _read_csv(filename: str) -> list[dict]:
    path = DATA_DIR / filename
    with open(path, newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def _blank_to_none(value: str | None) -> str | None:
    value = (value or "").strip()
    if value in ("", "-"):
        return None
    return value


def _num(value: str | None, default: float = 0.0) -> float:
    """Blank or '-' -> default (0.0), not a crash — CSVs get hand-edited
    and a stray empty cell shouldn't take seeding down with it."""
    cleaned = _blank_to_none(value)
    return float(cleaned) if cleaned is not None else default


def _load_portfolios() -> list[dict]:
    rows = _read_csv("portfolios.csv")
    return [
        {
            "key": r["portfolio_key"].strip(),
            "name": r["name"].strip(),
            "provider": _blank_to_none(r.get("provider")),
            "risk_band": int(r["risk_band"]),
            "max_equity_pct": _num(r["max_equity_pct"]),
            "min_horizon_years": _num(r["min_horizon_years"]),
            "liquidity_days": int(_num(r["liquidity_days"])),
            "reg28_compliant": r["reg28_compliant"].strip() in ("1", "true", "True"),
            "min_knowledge_band": int(_num(r["min_knowledge_band"], default=1)),
            "requires_emergency_fund": r["requires_emergency_fund"].strip() in ("1", "true", "True"),
            "underlying_fee_pct": _num(r["underlying_fee_pct"]),
            "description": _blank_to_none(r.get("description")),
        }
        for r in rows
    ]


def _load_products() -> list[dict]:
    rows = _read_csv("products.csv")
    return [
        {
            "key": r["product_key"].strip(),
            "name": r["name"].strip(),
            "provider": _blank_to_none(r.get("provider")),
            "tax_wrapper": r["tax_wrapper"].strip(),
            "min_initial_investment": _num(r["min_initial_investment"]),
            "min_monthly_investment": _num(r["min_monthly_investment"]),
            "annual_platform_fee_pct": _num(r["annual_platform_fee_pct"]),
            "advice_fee_pct": _num(r["advice_fee_pct"]),
            "min_term_years": _num(r["min_term_years"]),
            "description": _blank_to_none(r.get("description")),
            "spec_notes": _blank_to_none(r.get("spec_notes")),
        }
        for r in rows
    ]


def _load_mapping(known_product_keys: set[str], known_portfolio_keys: set[str]) -> list[tuple[str, str]]:
    """(product_key, portfolio_key) pairs. Skips (with a printed
    warning) any row referencing a key that doesn't actually exist in
    products.csv/portfolios.csv, and de-duplicates — both of which
    have shown up in hand-maintained versions of this file."""
    rows = _read_csv("product_portfolio_mapping.csv")
    seen: set[tuple[str, str]] = set()
    pairs: list[tuple[str, str]] = []
    for r in rows:
        product_key = (r.get("product_key") or "").strip()
        portfolio_key = (r.get("portfolio_key") or "").strip()
        if not product_key or not portfolio_key:
            continue
        if product_key not in known_product_keys:
            print(f"seed_data: skipping mapping row — unknown product_key '{product_key}'")
            continue
        if portfolio_key not in known_portfolio_keys:
            print(f"seed_data: skipping mapping row — unknown portfolio_key '{portfolio_key}'")
            continue
        pair = (product_key, portfolio_key)
        if pair in seen:
            continue
        seen.add(pair)
        pairs.append(pair)
    return pairs


def _load_returns() -> dict[str, list[tuple[float, float, float, float]]]:
    """portfolio_key -> [(horizon_years, expected_pct, lower_pct, upper_pct), ...],
    sorted by horizon. Converts the source file's decimal fractions to
    percentage numbers (x100) to match this app's convention everywhere
    else.

    De-duplicates by (portfolio_key, horizon_years) — DynamoDB's
    BatchWriteItem hard-rejects a whole batch if it contains the same
    primary key twice, and a source file this size (thousands of rows,
    regenerated by a separate script) is exactly the kind of thing
    that can pick up a duplicate row without anyone noticing until
    seeding fails on it. Last row for a given (portfolio, horizon)
    wins; a warning is printed so the underlying data issue is still
    visible, not just silently absorbed.
    """
    rows = _read_csv("portfolio_returns.csv")
    curves: dict[str, dict[float, tuple[float, float, float, float]]] = {}
    duplicate_count = 0
    for r in rows:
        key = r["portfolio_key"].strip()
        horizon = float(r["horizon_years"])
        point = (
            horizon,
            float(r["expected_return_pct"]) * 100,
            float(r["lower_return_pct"]) * 100,
            float(r["upper_return_pct"]) * 100,
        )
        bucket = curves.setdefault(key, {})
        if horizon in bucket:
            duplicate_count += 1
        bucket[horizon] = point  # last one wins for a given (portfolio, horizon)

    if duplicate_count:
        print(
            f"seed_data: portfolio_returns.csv had {duplicate_count} duplicate "
            f"(portfolio_key, horizon_years) rows — kept the last value for each"
        )

    return {key: sorted(points.values(), key=lambda p: p[0]) for key, points in curves.items()}


PORTFOLIOS = _load_portfolios()
PRODUCTS = _load_products()
_PRODUCT_KEYS = {p["key"] for p in PRODUCTS}
_PORTFOLIO_KEYS = {p["key"] for p in PORTFOLIOS}
PRODUCT_PORTFOLIO_MAPPING = _load_mapping(_PRODUCT_KEYS, _PORTFOLIO_KEYS)
PORTFOLIO_RETURNS = _load_returns()
